In [1]:
import yfinance as yf
import pandas as pd

In [2]:
tickers = ["SPY","QQQ","IWM","DIA","VTI","XLK","XLF","XLE","XLV","XLY","XLP","XLI","XLU","XLRE","XLB","EFA","EEM","EWJ","EWG","EWU","INDA","FXI","BND","IEF","TLT","SHY","LQD","HYG","GLD","SLV","USO","DBC","VNQ","VIXY","TAIL","USMV","MTUM","AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","IBIT","ETHA","COIN","BIL","TIP","SGOV"]

In [3]:
prices = yf.download(
    tickers,
    start="2015-01-01",
    end= pd.to_datetime('today').strftime('%Y-%m-%d'),
    auto_adjust=True
)["Close"]

prices.head()

[*********************100%***********************]  50 of 50 completed

Ticker,AAPL,AMZN,BIL,BND,COIN,DBC,DIA,EEM,EFA,ETHA,...,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.214888,15.4260,74.541565,60.186695,NaN,15.412329,142.082504,30.355049,43.780628,NaN,...,19.495251,25.714979,16.358444,46.341232,18.106762,36.067268,NaN,16.626709,57.292408,31.700203
2015-01-05,23.532724,15.1095,74.557861,60.361416,NaN,15.192513,139.607193,29.814817,42.747189,NaN,...,18.998352,24.651201,16.014481,45.258778,17.830359,35.813633,NaN,16.423426,57.000240,31.093906
2015-01-06,23.534939,14.7645,74.541565,60.536205,NaN,15.048789,138.449402,29.689545,42.262981,NaN,...,18.830042,24.289068,15.769731,44.701138,17.615374,35.768894,NaN,16.433943,56.808235,30.784113
2015-01-07,23.864950,14.9210,74.541565,60.572624,NaN,14.955792,140.206055,30.331577,42.732719,NaN,...,19.042429,24.340803,15.935098,45.037365,17.764540,36.380573,NaN,16.595167,58.143902,31.270929
2015-01-08,24.781898,15.0230,74.541565,60.477997,NaN,15.014974,142.737259,30.848310,43.310879,NaN,...,19.495251,24.887243,16.173235,45.939411,18.155025,36.932583,NaN,16.710825,59.137321,31.740023

In [4]:
prices.to_csv("../data/raw/prices.csv")

In [5]:
len(prices)

2805

In [6]:
prices.tail()

Ticker,AAPL,AMZN,BIL,BND,COIN,DBC,DIA,EEM,EFA,ETHA,...,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-23,266.179993,205.270004,91.559998,74.970001,160.240005,24.750000,488.010010,61.650002,104.470001,14.05,...,52.959999,55.150002,50.730000,174.830002,138.520004,88.970001,43.610001,46.680000,158.539993,114.989998
2026-02-24,272.140015,208.559998,91.580002,74.930000,162.029999,24.719999,491.790009,62.619999,104.660004,14.03,...,53.360001,55.099998,50.980000,176.979996,140.320007,89.739998,43.730000,47.200001,157.869995,116.739998
2026-02-25,274.230011,210.639999,91.589996,74.910004,183.940002,24.750000,494.820007,63.310001,105.660004,15.68,...,53.060001,54.869999,51.869999,175.600006,143.009995,89.010002,43.439999,47.360001,157.830002,117.089996
2026-02-26,272.950012,207.919998,91.599998,75.019997,181.059998,24.760000,494.859985,62.709999,105.570000,15.29,...,53.000000,55.049999,52.500000,176.699997,141.009995,88.860001,43.630001,47.180000,157.419998,117.050003
2026-02-27,264.179993,210.000000,91.620003,75.169998,175.850006,25.100000,489.660004,62.580002,105.379997,14.52,...,53.410000,55.919998,51.430000,177.139999,138.759995,90.010002,43.840000,47.730000,160.199997,116.860001