In [1]:

import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
import pandas as pd

from scripts.features.compute_returns import compute_log_returns
from scripts.features.compute_volatility import rolling_volatility
from scripts.features.technical_indicators import momentum

In [3]:
prices = pd.read_csv(
    "../data/raw/prices.csv",
    index_col=0,
    parse_dates=True
)

In [4]:
returns = compute_log_returns(prices)
volatility = rolling_volatility(returns)
mom = momentum(prices)

In [5]:
mom.tail(30)

,AAPL,AMZN,BIL,BND,COIN,DBC,DIA,EEM,EFA,ETHA,...,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Date,,,,,,,,,,,,,,,,,,,,,
2026-01-15,-0.059721,0.070183,0.002794,0.004149,-0.052769,0.062038,0.028169,0.096452,0.045723,0.114452,...,0.093616,0.096002,-0.001464,0.065922,0.021890,0.047311,0.039599,0.020835,0.023096,0.008309
2026-01-16,-0.059999,0.080671,0.003123,0.002798,-0.012449,0.047679,0.030999,0.100190,0.057143,0.166979,...,0.082790,0.074063,0.000005,0.090807,0.046279,0.039156,0.047663,0.022336,0.016992,0.016780
2026-01-20,-0.093648,0.018698,0.002958,-0.002967,-0.047952,0.069645,0.011658,0.077256,0.033748,0.079524,...,0.072366,0.087826,-0.021160,0.061866,0.003640,0.048374,0.033905,0.002359,0.013981,-0.024390
2026-01-21,-0.095078,0.017418,0.002738,0.001351,-0.074209,0.074369,0.020425,0.084512,0.037398,0.010601,...,0.090901,0.114107,-0.021757,0.071024,-0.003955,0.054854,0.041510,0.016709,0.025777,-0.001719
2026-01-22,-0.083478,0.025872,0.002848,0.002026,-0.099879,0.060295,0.021530,0.086836,0.038871,-0.013790,...,0.084300,0.106311,-0.027296,0.053805,-0.001929,0.056369,0.023638,0.005651,0.019253,0.002289
2026-01-23,-0.089294,0.030240,0.003176,0.003243,-0.104622,0.068021,0.014203,0.087645,0.038218,-0.009813,...,0.092240,0.105393,-0.042576,0.046054,-0.005892,0.069668,0.026630,-0.001408,0.016065,0.007858
2026-01-26,-0.067200,0.025992,0.002847,0.002022,-0.109498,0.073354,0.014843,0.087284,0.042112,-0.012179,...,0.091405,0.109308,-0.041629,0.043683,-0.001504,0.059652,0.019288,0.001401,0.014763,-0.002202
2026-01-27,-0.055340,0.052297,0.002627,0.001213,-0.110046,0.084581,0.006586,0.101095,0.057161,0.031165,...,0.083930,0.123756,-0.047105,0.049933,0.010373,0.063019,0.018016,0.015194,-0.003845,0.005244
2026-01-28,-0.063267,0.047141,0.002736,-0.000673,-0.104119,0.108937,0.011799,0.111416,0.049128,0.028959,...,0.092042,0.121694,-0.042119,0.046344,0.023034,0.051610,0.005415,0.010966,-0.009627,0.007613
2026-01-29,-0.054197,0.039565,0.002846,-0.000135,-0.139983,0.117491,0.014056,0.101312,0.054438,-0.054635,...,0.093374,0.123443,-0.029540,0.060350,0.010041,0.050928,0.015963,0.008613,-0.011947,0.006896
2026-01-30,-0.045538,0.036739,0.002955,0.002160,-0.138852,0.092576,0.017973,0.080241,0.049047,-0.100758,...,0.086439,0.141803,-0.024283,0.066529,-0.000625,0.075052,0.026766,0.013118,-0.000388,0.014739
2026-02-02,-0.003690,0.072671,0.002670,0.001550,-0.205767,0.051362,0.021874,0.054054,0.044930,-0.257846,...,0.076540,0.096385,-0.016385,0.060451,0.006653,0.087656,0.014363,-0.012969,0.001158,0.030587
2026-02-03,0.008307,0.023857,0.002670,-0.000070,-0.295230,0.058746,0.005550,0.048188,0.033622,-0.292822,...,0.088450,0.101941,-0.046321,0.056866,-0.017563,0.110149,0.009399,0.012646,-0.006063,0.005736
2026-02-04,0.053857,-0.032956,0.002779,-0.000476,-0.327027,0.060965,0.000645,0.026536,0.035402,-0.333061,...,0.092421,0.157537,-0.043262,0.045488,-0.058166,0.122886,0.018673,0.003962,-0.013031,-0.008012
2026-02-05,0.059847,-0.078117,0.002560,0.002771,-0.405847,0.051793,-0.001782,0.029551,0.024507,-0.406250,...,0.081834,0.156880,-0.041719,0.059131,-0.074387,0.134430,0.027155,0.029377,-0.030189,-0.028040
2026-02-06,0.073656,-0.146047,0.002889,0.004665,-0.327660,0.049388,0.017626,0.056269,0.047682,-0.338593,...,0.084421,0.143931,-0.029338,0.081226,-0.021561,0.121112,0.038328,0.032389,-0.002593,-0.040107
2026-02-09,0.059787,-0.156278,0.002670,0.002771,-0.305383,0.058952,0.012891,0.058978,0.052424,-0.308754,...,0.081227,0.149347,-0.032119,0.072686,-0.019158,0.103218,0.043210,0.022818,-0.006293,-0.055140
2026-02-10,0.052588,-0.160303,0.002670,0.006691,-0.331180,0.040966,0.012466,0.045910,0.048587,-0.351536,...,0.090478,0.156237,-0.031470,0.065821,-0.028885,0.086929,0.054653,0.038046,-0.013026,-0.049711
2026-02-11,0.056341,-0.158780,0.002779,0.003852,-0.393724,0.042790,0.019457,0.070423,0.061716,-0.390999,...,0.100349,0.169787,-0.027476,0.066033,-0.023962,0.089878,0.045688,0.040607,-0.003126,-0.051928
2026-02-12,0.007751,-0.156560,0.002670,0.006412,-0.448566,0.017529,0.006650,0.053853,0.048842,-0.434936,...,0.083692,0.123179,-0.045429,0.051622,-0.037941,0.084884,0.035757,0.048182,-0.011783,-0.050061
2026-02-13,-0.008484,-0.165379,0.003108,0.010871,-0.313273,0.029310,0.001981,0.052160,0.050171,-0.378172,...,0.088848,0.141567,-0.050028,0.050609,-0.040561,0.086682,0.043165,0.066269,0.004523,-0.053138
2026-02-17,0.033643,-0.158791,0.002779,0.012371,-0.311549,0.018567,0.004925,0.051840,0.047121,-0.395096,...,0.082580,0.127071,-0.041146,0.049011,-0.042165,0.074169,0.040986,0.068910,0.010466,-0.051186
2026-02-18,0.072547,-0.113463,0.002889,0.014983,-0.279629,0.031090,0.024996,0.067702,0.064477,-0.354654,...,0.100228,0.150840,-0.011466,0.070385,-0.006557,0.068966,0.047101,0.061685,0.014607,-0.017629
2026-02-19,0.053195,-0.114349,0.002779,0.012514,-0.268761,0.028632,0.007294,0.047717,0.050692,-0.356643,...,0.072908,0.131897,-0.024504,0.059990,-0.025033,0.063440,0.039711,0.071827,-0.006319,-0.042504
2026-02-20,0.066348,-0.103397,0.002999,0.011969,-0.232096,0.036226,0.006089,0.062010,0.055120,-0.328372,...,0.069467,0.122061,-0.024531,0.070876,-0.027609,0.068312,0.058824,0.084758,-0.009287,-0.042163
2026-02-23,0.074137,-0.141704,0.002670,0.013041,-0.261397,0.023573,-0.004714,0.043677,0.045014,-0.367117,...,0.059836,0.121163,-0.044093,0.064608,-0.045282,0.073091,0.057212,0.096804,0.006731,-0.066109
2026-02-24,0.066500,-0.125241,0.002889,0.011274,-0.241006,0.017703,-0.003359,0.058307,0.041704,-0.359361,...,0.066560,0.119464,-0.045497,0.076652,-0.039430,0.084078,0.060893,0.101003,-0.001455,-0.045618
2026-02-25,0.062789,-0.139120,0.002889,0.011821,-0.127544,0.005280,0.010967,0.049221,0.034969,-0.313184,...,0.061625,0.104691,-0.021321,0.063856,-0.034043,0.070346,0.053091,0.090490,0.015310,-0.045644
2026-02-26,0.065377,-0.144397,0.002889,0.013716,-0.135463,-0.007217,0.010904,0.032263,0.045144,-0.327617,...,0.061061,0.099900,-0.009247,0.076520,-0.055083,0.079446,0.068054,0.088853,0.020154,-0.038762
2026-02-27,0.023801,-0.131262,0.002889,0.015606,-0.117130,-0.007905,0.000118,0.035407,0.036287,-0.312174,...,0.068200,0.107108,-0.039589,0.068009,-0.055219,0.095946,0.059705,0.101546,0.041477,-0.035729

In [6]:
mom.describe()

,AAPL,AMZN,BIL,BND,COIN,DBC,DIA,EEM,EFA,ETHA,...,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
count,2785.000000,2785.000000,2785.000000,2785.000000,1205.000000,2785.000000,2785.000000,2785.000000,2785.000000,382.000000,...,2785.000000,2785.000000,2785.000000,2785.000000,2785.000000,2785.000000,2592.000000,2785.000000,2785.000000,2785.000000
mean,0.020329,0.022932,0.001473,0.001562,0.022656,0.004793,0.010065,0.006236,0.007255,0.007327,...,0.008731,0.009329,0.010373,0.011092,0.016522,0.006940,0.006667,0.008203,0.007929,0.011283
std,0.077350,0.086739,0.001567,0.013874,0.269480,0.048953,0.042946,0.051656,0.044977,0.231430,...,0.054405,0.083163,0.056109,0.052145,0.055924,0.035257,0.051835,0.046693,0.040357,0.057505
min,-0.267721,-0.312525,-0.000633,-0.054078,-0.641508,-0.273154,-0.335695,-0.301605,-0.320046,-0.434936,...,-0.341640,-0.562808,-0.401755,-0.394795,-0.288348,-0.225641,-0.379967,-0.347147,-0.251451,-0.338852
25%,-0.029430,-0.025233,0.000000,-0.005286,-0.158532,-0.024369,-0.010767,-0.025333,-0.015366,-0.160519,...,-0.022936,-0.033998,-0.017558,-0.016327,-0.013978,-0.012850,-0.018831,-0.020161,-0.015666,-0.016333
50%,0.023669,0.027296,0.001071,0.002184,-0.032254,0.007807,0.013643,0.008485,0.010896,-0.026213,...,0.010710,0.007563,0.013601,0.011269,0.020132,0.008683,0.008657,0.011323,0.009903,0.013214
75%,0.073882,0.071948,0.003084,0.009187,0.141878,0.036655,0.033874,0.039429,0.031970,0.116136,...,0.042758,0.053196,0.042638,0.040812,0.052148,0.029005,0.035770,0.037847,0.033225,0.042453
max,0.345292,0.351757,0.004836,0.091438,1.242634,0.226836,0.237561,0.164793,0.180611,0.645968,...,0.246676,0.420787,0.209657,0.229650,0.248403,0.193708,0.287117,0.274872,0.299115,0.269769

In [7]:

feature_matrix = pd.concat(
    [
        returns.add_suffix("_ret"),
        volatility.add_suffix("_vol"),
        mom.add_suffix("_mom")
    ],
    axis=1
)
# Keep vol/mom even if NaN, drop only raw returns
ret_cols = [col for col in feature_matrix.columns if col.endswith('_ret')]
feature_matrix = feature_matrix.dropna(subset=ret_cols)  # Only raw returns matter!

print(f"✅ Ret-only dropna: {len(feature_matrix)} rows")

✅ Ret-only dropna: 2805 rows

In [8]:
feature_matrix.head()

,AAPL_ret,AMZN_ret,BIL_ret,BND_ret,COIN_ret,DBC_ret,DIA_ret,EEM_ret,EFA_ret,ETHA_ret,...,XLB_mom,XLE_mom,XLF_mom,XLI_mom,XLK_mom,XLP_mom,XLRE_mom,XLU_mom,XLV_mom,XLY_mom
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,-0.028576,-0.020731,0.000219,0.002899,0.0,-0.014365,-0.017575,-0.017957,-0.023888,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,0.000094,-0.023098,-0.000219,0.002892,0.0,-0.009505,-0.008328,-0.004211,-0.011392,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,0.013925,0.010544,0.000000,0.000601,0.0,-0.006199,0.012608,0.021394,0.011053,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,0.037703,0.006813,0.000000,-0.001563,0.0,0.003949,0.017892,0.016893,0.013439,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
feature_matrix.describe()

,AAPL_ret,AMZN_ret,BIL_ret,BND_ret,COIN_ret,DBC_ret,DIA_ret,EEM_ret,EFA_ret,ETHA_ret,...,XLB_mom,XLE_mom,XLF_mom,XLI_mom,XLK_mom,XLP_mom,XLRE_mom,XLU_mom,XLV_mom,XLY_mom
count,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,2805.000000,...,2785.000000,2785.000000,2785.000000,2785.000000,2785.000000,2785.000000,2592.000000,2785.000000,2785.000000,2785.000000
mean,0.000852,0.000931,0.000074,0.000079,-0.000223,0.000174,0.000441,0.000258,0.000313,-0.000211,...,0.008731,0.009329,0.010373,0.011092,0.016522,0.006940,0.006667,0.008203,0.007929,0.011283
std,0.018143,0.020655,0.000166,0.003367,0.035584,0.011181,0.010957,0.012892,0.010861,0.018080,...,0.054405,0.083163,0.056109,0.052145,0.055924,0.035257,0.051835,0.046693,0.040357,0.057505
min,-0.137708,-0.151398,-0.000438,-0.055919,-0.306537,-0.082778,-0.136521,-0.133294,-0.116424,-0.224348,...,-0.341640,-0.562808,-0.401755,-0.394795,-0.288348,-0.225641,-0.379967,-0.347147,-0.251451,-0.338852
25%,-0.007309,-0.008874,0.000000,-0.001503,0.000000,-0.005854,-0.003814,-0.006477,-0.004616,0.000000,...,-0.022936,-0.033998,-0.017558,-0.016327,-0.013978,-0.012850,-0.018831,-0.020161,-0.015666,-0.016333
50%,0.000943,0.001074,0.000077,0.000128,0.000000,0.000784,0.000736,0.000734,0.000637,0.000000,...,0.010710,0.007563,0.013601,0.011269,0.020132,0.008683,0.008657,0.011323,0.009903,0.013214
75%,0.009840,0.011407,0.000218,0.001771,0.000000,0.006614,0.005497,0.007523,0.005883,0.000000,...,0.042758,0.053196,0.042638,0.040812,0.052148,0.029005,0.035770,0.037847,0.033225,0.042453
max,0.142617,0.132178,0.000765,0.041334,0.270902,0.046874,0.104533,0.077451,0.081332,0.166997,...,0.246676,0.420787,0.209657,0.229650,0.248403,0.193708,0.287117,0.274872,0.299115,0.269769

In [10]:
feature_matrix.to_csv("../data/processed/feature_matrix.csv")